---
Name: mysiteroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'courses//$Action/$ID/$Name': 'CourseController'
    'teams//$Action/$ID/$Name': 'TeamController'
    'player/': 'PlayerController'
    '': 'HomeController'
