---
Name: restfulapi
After: 'framework/*','cms/*'
---
# ---------------------------------
# Routing
Director:
  rules:
    'api': 'RESTfulAPI'
# ---------------------------------
# Permissions / Uncomment or create your own
#Group:
#  extensions:
#    - RESTfulAPI_GroupExtension